# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 17:14
from __future__ import unicode_literals

from django.db import migrations
import downloads.fields


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=downloads.fields.ValidatedFileField(help_text='Only PDF and ZIP files.', upload_to='downloads', verbose_name='file'),
        ),
    ]
